server:
  port: 8080

#swagger3 生产环境下ture
#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true

spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/supermusic?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,log4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123

  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

 #swagger3导致启动失败问题（原因是在springboot2.6.0中将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错，解决办法是切换会原先的AntPathMatcher）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



  security:
    user:
      name: 123
      password: 123

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1444504585@qq.com
    password: ozwukvkehsgdfhgi
    port: 587



  #mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml            # 配置mapper.xml路径
  check-config-location: true                         # 检查xml文件是否存在
  configuration:
    map-underscore-to-camel-case: true                # 开启驼峰命名法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.torch.supermusic.entity    # 实体类存放位置
  global-config:
    refresh-mapper: true


jwt:
  secret: supermusic.com
#  token过期时间：5天
  expiration: 432000000
